### ISSUE TITLE
Debug message still needed?

### ISSUE THREAD

**Issue by tintincastro** [websitemacherei/grav-plugin-lazysizes#2]
Hello,

In the markdown initialized event, the plugin outputs its own configuration to the debugger.
Is it still needed? Because it makes the debugger a bit crowded, especially on modular pages (see example below).

![debugger](https://user-images.githubusercontent.com/25725603/80916242-c41b0e00-8d57-11ea-8eb9-db973496c132.gif)

Have a nice day !

**Comment by janstuemmel** [comment]
done
